language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install numpy
  - pip install tada0-toddler-neural-network
# command to run tests
script:
  - python PyPI/toddlernetwork/neural_network.py
  - python PyPI/toddlernetwork/nn_exceptions.py